CREATE TABLE {{TABLE_NAME}} (
    id BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    created_by VARCHAR(50),
    created_at TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP(6),
    updated_by VARCHAR(50),
    updated_at TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    version INT NOT NULL DEFAULT 0,
    source_id BIGINT,
    lifecycle_status TINYINT UNSIGNED NOT NULL,
    upload_id BIGINT{{MIGRATION_COLUMNS}}
);
{{MIGRATION_FK_CONSTRAINTS}}
